// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYfKDIirqH0srfb1zKSAFlqcjyeIjmpS0',
    appId: '1:257755589958:web:3dcdd0d3e4256ab8f2c947',
    messagingSenderId: '257755589958',
    projectId: 'mcs-proyek-852d2',
    authDomain: 'mcs-proyek-852d2.firebaseapp.com',
    databaseURL: 'https://mcs-proyek-852d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mcs-proyek-852d2.firebasestorage.app',
    measurementId: 'G-BW76B3RFY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVPDAaYbukIdIdj3C_q3bUtJWCyVeZ02o',
    appId: '1:257755589958:android:d6ccd12b6c46e637f2c947',
    messagingSenderId: '257755589958',
    projectId: 'mcs-proyek-852d2',
    databaseURL: 'https://mcs-proyek-852d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mcs-proyek-852d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxlMEeaNHA3DuJ9uA-VXq9cHX4TvHr6-c',
    appId: '1:257755589958:ios:14535a751ce6e0baf2c947',
    messagingSenderId: '257755589958',
    projectId: 'mcs-proyek-852d2',
    databaseURL: 'https://mcs-proyek-852d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mcs-proyek-852d2.firebasestorage.app',
    iosBundleId: 'com.example.mcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxlMEeaNHA3DuJ9uA-VXq9cHX4TvHr6-c',
    appId: '1:257755589958:ios:14535a751ce6e0baf2c947',
    messagingSenderId: '257755589958',
    projectId: 'mcs-proyek-852d2',
    databaseURL: 'https://mcs-proyek-852d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mcs-proyek-852d2.firebasestorage.app',
    iosBundleId: 'com.example.mcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYfKDIirqH0srfb1zKSAFlqcjyeIjmpS0',
    appId: '1:257755589958:web:c072f26246117510f2c947',
    messagingSenderId: '257755589958',
    projectId: 'mcs-proyek-852d2',
    authDomain: 'mcs-proyek-852d2.firebaseapp.com',
    databaseURL: 'https://mcs-proyek-852d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mcs-proyek-852d2.firebasestorage.app',
    measurementId: 'G-1GHENR67VV',
  );
}
